//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 04:02:11 PM PDT 
//


package com.nagen.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nagen.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mobile_QNAME = new QName("http://www.magic.com/mobile", "mobile");
    private final static QName _Tmobile_QNAME = new QName("http://www.magic.com/mobile", "tmobile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nagen.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mobile }
     * 
     */
    public Mobile createMobile() {
        return new Mobile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mobile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.magic.com/mobile", name = "mobile")
    public JAXBElement<Mobile> createMobile(Mobile value) {
        return new JAXBElement<Mobile>(_Mobile_QNAME, Mobile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mobile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.magic.com/mobile", name = "tmobile")
    public JAXBElement<Mobile> createTmobile(Mobile value) {
        return new JAXBElement<Mobile>(_Tmobile_QNAME, Mobile.class, null, value);
    }

}
